name: Test
on: push

jobs:
  TestJob:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  

      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v17
        with:
          files: test3/*
          since_last_remote_commit: "true"

      - name: Change detection
        if: steps.changed-files-specific.outputs.any_modified == 'true'
        run: echo "The files under the test3 directory have been changed!"

      - name: No change detection
        if: steps.changed-files-specific.outputs.any_modified == 'false'
        run: echo "The files under the test3 directory were not changed!"