name: Test
on: push

jobs:
  TestJob:
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: |
          if [ -e ../test.txt ]; then \
               curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/octocat; \
          else \
              curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/octocat; \
          fi

