name: Test
on: push

jobs:
  TestJob:
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ github.ref_name }}

    steps:
      - name: Test1
        id: test1
        run: |
          echo "Hi!" >> test.txt
          curl -s -X POST -H "X-ChatWorkToken: ${{ secrets.ABCDEF }}" -F "file=@test.txt" -F $'message=【 ブランチ：${{ github.ref_name }} 】\n${{ github.event.head_commit.message }}(${{ github.event.head_commit.author.name }})' "https://api.chatwork.com/v2/rooms/${{ secrets.ROOM_ID }}/files";

