name: Test
on: push

jobs:
  TestJob:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.before }}
          fetch-depth: 2

      - name: git log
        run: |
          git log --pretty=oneline        

      - name: change git config
        run: git config diff.renames false

      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v17
        with:
          files: '**'
          since_last_remote_commit: "true"

      - name: Change detection
        #if: "!(steps.changed-files-specific.outputs.other_changed_files == '')"
        run: |
          echo "${{ steps.changed-files-specific.outputs.all_changed_files }}"
          .github/workflows/get_diff.sh "${{ steps.changed-files-specific.outputs.all_changed_files }}"
          # for file in ${{ steps.changed-files-specific.outputs.other_changed_files }}; do
          #   echo "$file was changed"
          # done

      # - name: No change detection
      #   if: steps.changed-files-specific.outputs.other_changed_files == ''
      #   run: echo "The files under the directory were not changed!"
