name: Test
on: push

jobs:
  TestJob:
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ github.ref_name }}

    steps:
      - name: Check commits count
        id: check_commits_count
        run: |
          echo "commits_count=$(echo "$(( 2 + $(echo "${{ join(github.event.commits.*.id, ',') }}" | tr ',' '\n' | grep -c '')))")" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}
          fetch-depth: ${{ steps.check_commits_count.outputs.commits_count }}

      - name: Setup
        run: |
          git config diff.renames false
          git config core.quotepath false
          git status

      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v34
        with:
          files: '**'
          files_ignore: test1/**
          since_last_remote_commit: "true"
          separator: ","

      - name: Test2
        run: |
          echo "git diff (modified files(acmrd)) : ${{ steps.changed-files-specific.outputs.other_modified_files }}"
          echo "git diff (modified files(acmr)) : ${{ steps.changed-files-specific.outputs.other_changed_files }}" 
          
      - name: Test3
        id: test3
        run: |
          mkdir test
          mkdir test
          echo "ok"

      - name: Test1
        if: ${{ success() || failure() }}
        id: test1
        env:
          ABCDEF: ${{ secrets.ABCDEF }}
          ROOM_ID: ${{ secrets.ROOM_ID }}
          MESSAGE: ${{ github.event.head_commit.message }}
          AUTHOR: ${{ github.event.head_commit.author.name }}
        run: |
          # echo "Hi!" >> test.txt
          .github/workflows/abc.sh
