name: Test
on: push

jobs:
  TestJob:
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ github.ref_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: test
        run: |
          .github/workflows/get_diff.sh

