name: Test
on: push

jobs:
  TestJob:
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ github.ref_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test1
        id: test1
        run: |
          echo "::set-output name=param::12345"

      - name: Test2
        env:
          PARAM: ${{steps.test1.outputs.param}}
        run: |
          .github/workflows/get_diff.sh

