name: Test
on: push

jobs:
  TestJob:
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: |
          if [ -e ../test.txt ]; then \
              echo "file is found." \
          else \
              echo "file is NOT found." \
          fi
          if [ -s ../test.txt ]; then \
            echo "file is NOT empty." \
          else \
            echo "file is empty." \
          fi

