name: Test
on: push

jobs:
  TestJob:
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ github.ref_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH }}

      - name: Test1
        id: test1
        env:
          ABCDEF: ${{ secrets.ABCDEF }}
          ROOM_ID: ${{ secrets.ROOM_ID }}
          MESSAGE: ${{ github.event.head_commit.message }}
          AUTHOR: ${{ github.event.head_commit.author.name }}
        run: |
          echo "" >> test.txt
          .github/workflows/get_diff.sh
          

