name: Test
on: push

jobs:
  TestJob:
    runs-on: ubuntu-latest

    steps:
      - name: Objects
        run: echo "${{ toJson(github) }}"

      - name: Commits
        run: echo "${{ toJson(github.event.commits) }}"
      
      # - name: Commits
      #   run: |
      #     echo "commits ${{ toJson(github.event.commits) }}"
      #     echo "added ${{ github.event.commits[0][added] }}"
      #     echo "modified ${{ github.event.commits[0][modified] }}"
      #     echo "removed ${{ github.event.commits[0][removed] }}"

      - name: Commits Length
        run: |
          echo '${{ toJSON(github.event.commits) }}' | jq '. | length'

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  

      - name: change git config
        run: git config diff.renames false

      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v17
        with:
          files: test3/*
          since_last_remote_commit: "true"

      - name: Change detection
        if: steps.changed-files-specific.outputs.any_modified == 'true'
        run: |
          echo "The files under the test3 directory have been changed!"
          for file in ${{ steps.changed-files-specific.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
          for file in ${{ steps.changed-files-specific.outputs.deleted_files }}; do
            echo "$file was deleted"
          done

      - name: No change detection
        if: steps.changed-files-specific.outputs.any_modified == 'false'
        run: echo "The files under the test3 directory were not changed!"
