name: Test
on: push

jobs:
  TestJob:
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ github.ref_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH }}

      - name: Test1
        id: test1
        env:
          TEST: ${{ secrets.TEST }}
        run: |
          echo "Hi!" >> test.txt
          .github/workflows/get_diff.sh

